### ISSUE TITLE
Every time I run only ooniprobe it fails

### ISSUE THREAD

**Issue by hellais** [ooni/probe-legacy#41]
@Baccount commented on [Fri May 11 2018](https://github.com/ooni/probe/issues/793)

I ran ooniprobe using this command
`ooniprobe -i /usr/local/share/ooniprobe/current.deck`
When I visit http://2lzg3f4r3eapfi6j.onion/ I get this error `{"error": 405}`

Error message
Report ID: 20180510T231502Z_AS22773_nI1z1SG5zmHtgeWtEqStFytpCUM1qTwodV31sfZbefNuSlqrB0
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.

---

@hellais commented on [Thu Jul 26 2018](https://github.com/ooni/probe/issues/793#issuecomment-408062666)

@Baccount can you clarify where you installed ooniprobe from and what is the content of `current.deck`?
I don't see that onion as part of the OONI backends, so maybe you are running an outdated version of ooniprobe.

---

@Baccount commented on [Sat Jul 28 2018](https://github.com/ooni/probe/issues/793#issuecomment-408573648)

I still get this error after the test finishes. I installed ooniprobe from Brew and it is up to date.
```
Report ID: 20180728T005343Z_AS22773_lXxlxwe8nTsdiq7ZEzRVz05tPbpYIImszsys1lZmHumVP5G4P0
[!] Lookup http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
Error performing HTTP request: http://www.acdi-cida.gc.ca
```
Here is the information in `current.deck`
```
name: Test the Web
description: "This deck examines whether (and how) websites are blocked and
tries to detect censorship and/or surveillance systems in your network. The Web
Connectivity test examines whether access to websites is blocked through DNS
tampering, TCP/IP blocking, or by a transparent HTTP proxy. The
HTTP Header Field Manipulation test tries to detect censorship and/or
surveillance systems in your network by sending HTTP headers to an echo server
that have variations in capitalization."
schedule: "@daily"
icon: "fa-unlink"
tasks:
- name: Runs the HTTP Header Field Manipulation test
  ooni:
    test_name: http_header_field_manipulation

- name: Runs the Web Connectivity Test
  ooni:
    test_name: web_connectivity
    file: $citizenlab_global_urls

- name: Runs the Web Connectivity Test
  ooni:
    test_name: web_connectivity
    file: $citizenlab_${probe_cc}_urls

```
